---
- name: Ensure phpMyAdmin is installed.
  yum: name=phpmyadmin state=installed enablerepo={{ phpmyadmin_enablerepo }}
  notify: restart apache
  
- name: Configure Apache Alias
  template:
    src: "phpmyadmin-confd-{{ ansible_os_family }}.j2"
    dest: /etc/httpd/conf.d/phpMyAdmin.conf
  notify: restart apache